# Generated by Django 3.2 on 2022-02-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_salary_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Active', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance_table',
        ),
        migrations.DeleteModel(
            name='Complaint_table',
        ),
        migrations.DeleteModel(
            name='Leave_table',
        ),
        migrations.DeleteModel(
            name='Reg_employee',
        ),
        migrations.DeleteModel(
            name='Salary_table',
        ),
    ]
