# Generated by Django 3.2 on 2022-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_customer_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Subcategory', models.CharField(max_length=200)),
            ],
        ),
    ]
