# Generated by Django 3.2 on 2022-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_category_table_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Sub_Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='category_table',
            name='Category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
