# Generated by Django 3.2 on 2022-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_cart_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
