# Generated by Django 3.2 on 2022-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_cart_table_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.CharField(max_length=200)),
                ('usid', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
