# Generated by Django 3.2 on 2022-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_purchase_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_table',
            name='status',
            field=models.CharField(default='ordered', max_length=200),
        ),
    ]
