# Generated by Django 3.2 on 2022-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_purchase_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_table',
            name='autoname',
            field=models.CharField(default='nil', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase_table',
            name='total',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
