# Generated by Django 3.2 on 2022-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_notification_table',
            name='autoid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
