# Generated by Django 3.2 on 2022-02-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_notification_table_orid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_notification_table',
            name='shopid',
        ),
    ]
