# Generated by Django 3.2 on 2022-03-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_auto_20220223_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Category',
        ),
        migrations.DeleteModel(
            name='Auto_notification_table',
        ),
        migrations.DeleteModel(
            name='Auto_reg',
        ),
        migrations.DeleteModel(
            name='Cart_table',
        ),
        migrations.DeleteModel(
            name='Category_table',
        ),
        migrations.DeleteModel(
            name='Customer_reg',
        ),
        migrations.DeleteModel(
            name='Product_table',
        ),
        migrations.DeleteModel(
            name='Purchase_table',
        ),
        migrations.RenameField(
            model_name='shop_reg',
            old_name='Email',
            new_name='Ardno',
        ),
        migrations.RenameField(
            model_name='shop_reg',
            old_name='Address',
            new_name='Cardcount',
        ),
        migrations.RenameField(
            model_name='shop_reg',
            old_name='Latitude',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='shop_reg',
            old_name='Longitude',
            new_name='Panchayth',
        ),
    ]
