# Generated by Django 3.2 on 2022-03-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_auto_20220324_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_reg',
            name='Active',
        ),
    ]
