# Generated by Django 3.2 on 2022-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_stock_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_table',
            old_name='Date',
            new_name='Month',
        ),
        migrations.AddField(
            model_name='stock_table',
            name='Year',
            field=models.CharField(default='2022', max_length=200),
        ),
    ]
