# Generated by Django 3.2 on 2022-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_purchase_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_table',
            old_name='shopusername',
            new_name='shopname',
        ),
        migrations.AddField(
            model_name='purchase_table',
            name='shopid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
