# Generated by Django 3.2 on 2022-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_auto_20220326_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_reg',
            name='Star1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='shop_reg',
            name='Star2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='shop_reg',
            name='Star3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='shop_reg',
            name='Star4',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
